package br.com.helpthenext.enums;

public enum Causas {
	
	PESSOAS_COM_DEFICIENCIA,
	SAUDE,
	PROTECAO_ANIMAL,
	PARTICIPACAO_CIDADA,
	MEIO_AMBIENTE,
	IDOSOS,
	EDUCACAO,
	DEFESA_DE_DIREITOS,
	CULTURA_ESPORTE_ARTE,
	CRIANCAS_JOVENS,
	CONSUMO_CONSCIENTE,
	CAPACITAÇÃO_PROFISSIONAL,
	COMBATE__PROBREZA,
	OUTRAS;
	
}
